apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: frontend-nginx
  name: frontend-nginx
spec:
  replicas: 4
  selector:
    matchLabels:
      app: frontend-nginx
  template:
    metadata:
      labels:
        app: frontend-nginx
    spec:
      containers:
      - image: 347751175815.dkr.ecr.ap-northeast-2.amazonaws.com/ecr_nginx:f0a0ccf
        name: frontend-nginx





















